using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ApiMenu;
//
//    var drinks = Drinks.FromJson(jsonString);

namespace ApiMenu
{
    public partial class Foods
    {
        [JsonProperty("meals", Required = Required.Always)]
        public Dictionary<string, string>[] Foodees { get; set; }
    }


    public partial class Foods
    {
        public static Foods FromJson(string json) => JsonConvert.DeserializeObject<Foods>(json, ApiMenu.FoodsConverter.Settings);
    }

    public static class FoodsSerialize
    {
        public static string ToJson(this Foods self) => JsonConvert.SerializeObject(self, ApiMenu.FoodsConverter.Settings);
    }

    internal static class FoodsConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
